### ISSUE TITLE
read_gateway command causes MS 500 error

### ISSUE THREAD

**Issue by iychoi** [syndicate-storage/syndicate-core#27]
```
[2017-06-06 07:16:26,295] [DEBUG] [client:191] (25375) MS URL http://syndicate-ms-datasets.appspot.com:80//API is NOT confidential!
[2017-06-06 07:16:26,299] [DEBUG] [client:270] (25375) As jcnelson@cs.princeton.edu, call read_gateway(ag_imicrobe )
[2017-06-06 07:16:27,724] [ERROR] [syndicate:1138] (25375) HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/usr/bin/syndicate", line 1135, in main
    result = client.ms_rpc( rpc_client, method_name, *args, **kw )
  File "/usr/lib/python2.7/dist-packages/syndicate/util/client.py", line 272, in ms_rpc
    ret = method_callable( *args, **kw )
  File "/usr/lib/python2.7/dist-packages/syndicate/ms/jsonrpc.py", line 434, in default
    return self.request()
  File "/usr/lib/python2.7/dist-packages/syndicate/ms/jsonrpc.py", line 481, in request
    response = urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
Help for 'read_gateway':

   Read a gateway.

   Positional arguments:
      name (str):
...
```

I don't see this at uofa opencloud demo setup yet. (Not sure if it can happen)

**Comment by iychoi** [comment]
This was because we've exceeded quota.
